project:
  type: website
  output-dir: docs

website:
  title: "J Wyatt Koma"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research Portfolio
      - href: publications.qmd
        text: Publications
      - href: media/Koma-CV.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

resources:
  - "media/*"
