project:
  type: website
  output-dir: docs

website:
  title: "J Wyatt Koma"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: media/Koma-CV-07-16-2025.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

resources:
  - "media/*"